export const DATA_ATTR = {
  mapCenterLat: "data-map-center-lat",
  mapCenterLng: "data-map-center-lng",
  mapZoom: "data-map-zoom",
  mapType: "data-map-type",
  controlZoom: "data-control-zoom",
  controlStreetView: "data-control-streetview",
  controlFullscreen: "data-control-fullscreen",
  controlMapType: "data-control-maptype",
  controlScale: "data-control-scale",
  layerTraffic: "data-layer-traffic",
  layerTransit: "data-layer-transit",
  layerBicycling: "data-layer-bicycling",
  tooltipType: "data-tooltip-type",
  tooltipTrigger: "data-tooltip-trigger",
  tooltipAutoOpen: "data-tooltip-auto-open",
  tooltipTemplate: "data-tooltip-template",
  tooltipBgColor: "data-tooltip-bg-color",
  tooltipTextColor: "data-tooltip-text-color",
  tooltipBorderRadius: "data-tooltip-border-radius",
  tooltipPadding: "data-tooltip-padding",
  tooltipFontSize: "data-tooltip-font-size",
  tooltipFontFamily: "data-tooltip-font-family",
  tooltipBorderWidth: "data-tooltip-border-width",
  tooltipBorderColor: "data-tooltip-border-color",
  tooltipBorderStyle: "data-tooltip-border-style",
  tooltipBoxShadow: "data-tooltip-box-shadow",
  tooltipMaxWidth: "data-tooltip-max-width",
  legendEnabled: "data-legend-enabled",
  legendPosition: "data-legend-position",
  legendBgColor: "data-legend-bg-color",
  legendTextColor: "data-legend-text-color",
  customCss: "data-custom-css",
  markerLat: "data-marker-lat",
  markerLng: "data-marker-lng",
  markerVisible: "data-marker-visible",
  markerTitle: "data-marker-title",
  markerDescription: "data-marker-description",
  markerColor: "data-marker-color",
  markerIcon: "data-marker-icon",
  legendLabel: "data-legend-label",
  legendColor: "data-legend-color",
};

export const DEFAULTS = {
  mapCenterLat: 37.7749,
  mapCenterLng: -122.4194,
  mapZoom: 12,
  mapType: "roadmap",
  tooltipType: "infowindow",
  tooltipTrigger: "click",
  legendPosition: "TOP_LEFT",
  legendBgColor: "white",
  legendTextColor: "black",
  tooltipPadding: "16px",
};
